title:
  de: Seite
  en: Page

icon: 📄

tabs:
  content:
    label:
      de: Inhalt
      en: Content
    icon: draft
    columns:
      - width: 2/3
        sections:
          text: sections/text

      - width: 1/3
        sections:
          meta: sections/meta

  images: tabs/images
